# https://chat.deepseek.com/share/p8uktv119yrjzwb3nd
import requests

BASE_URL = "https://aes.cryptohack.org/forbidden_fruit"

def get_ct(pt: bytes):
    data = requests.get(f"{BASE_URL}/encrypt/{pt.hex()}/")
    return data.json()

a1 = b'A'*16
c1 = bytes.fromhex(get_ct(b'A'*16)["ciphertext"])
t1 = bytes.fromhex(get_ct(b'A'*16)["tag"])
iv = bytes.fromhex(get_ct(b'A'*16)["nonce"])
print(a1)
print(c1)
print(t1)

a2 = b'B'*16
c2 = bytes.fromhex(get_ct(b'B'*16)["ciphertext"])
t2 = bytes.fromhex(get_ct(b'B'*16)["tag"])
print(a2)
print(c2)
print(t2)

# https://github.com/jvdsn/crypto-attacks/blob/master/attacks/gcm/forbidden_attack.py
from sage.all import *

x = GF(2)["x"].gen()
gf2e = GF(2 ** 128, name="y", modulus=x ** 128 + x ** 7 + x ** 2 + x + 1)


# Converts an integer to a gf2e element, little endian.
def _to_gf2e(n):
    return gf2e([(n >> i) & 1 for i in range(127, -1, -1)])


# Converts a gf2e element to an integer, little endian.
def _from_gf2e(p):
    n = 0
    polynomial = p.polynomial()
    for i in range(128):
        n <<= 1
        n |= int(polynomial[i])

    return n

def _ghash(h, a, c):
    la = len(a)
    lc = len(c)
    p = gf2e(0)
    for i in range(la // 16):
        p += _to_gf2e(int.from_bytes(a[16 * i:16 * (i + 1)], byteorder="big"))
        p *= h

    if la % 16 != 0:
        p += _to_gf2e(int.from_bytes(a[-(la % 16):] + bytes(16 - la % 16), byteorder="big"))
        p *= h

    for i in range(lc // 16):
        p += _to_gf2e(int.from_bytes(c[16 * i:16 * (i + 1)], byteorder="big"))
        p *= h

    if lc % 16 != 0:
        p += _to_gf2e(int.from_bytes(c[-(lc % 16):] + bytes(16 - lc % 16), byteorder="big"))
        p *= h

    p += _to_gf2e(((8 * la) << 64) | (8 * lc))
    p *= h
    return p


def recover_possible_auth_keys(a1, c1, t1, a2, c2, t2):
    """
    Recovers possible authentication keys from two messages encrypted with the same authentication key.
    More information: Joux A., "Authentication Failures in NIST version of GCM"
    :param a1: the associated data of the first message (bytes)
    :param c1: the ciphertext of the first message (bytes)
    :param t1: the authentication tag of the first message (bytes)
    :param a2: the associated data of the second message (bytes)
    :param c2: the ciphertext of the second message (bytes)
    :param t2: the authentication tag of the second message (bytes)
    :return: a generator generating possible authentication keys (gf2e element)
    """
    h = gf2e["h"].gen()
    p1 = _ghash(h, a1, c1) + _to_gf2e(int.from_bytes(t1, byteorder="big"))
    p2 = _ghash(h, a2, c2) + _to_gf2e(int.from_bytes(t2, byteorder="big"))
    for h, _ in (p1 + p2).roots():
        # print(h)
        yield h

def forge_tag(h, a, c, t, target_a, target_c):
    """
    Forges an authentication tag for a target message given a message with a known tag.
    This method is best used with the authentication keys generated by the recover_possible_auth_keys method.
    More information: Joux A., "Authentication Failures in NIST version of GCM"
    :param h: the authentication key to use (gf2e element)
    :param a: the associated data of the message with the known tag (bytes)
    :param c: the ciphertext of the message with the known tag (bytes)
    :param t: the known authentication tag (bytes)
    :param target_a: the target associated data (bytes)
    :param target_c: the target ciphertext (bytes)
    :return: the forged authentication tag (bytes)
    """
    ghash = _from_gf2e(_ghash(h, a, c))
    target_ghash = _from_gf2e(_ghash(h, target_a, target_c))
    return (ghash ^ int.from_bytes(t, byteorder="big") ^ target_ghash).to_bytes(16, byteorder="big")

H = list(recover_possible_auth_keys(b'CryptoHack', c1, t1, b'CryptoHack', c2, t2))[0]

def xor_bytes(a, b):
    return bytes(x ^ y for x, y in zip(a, b))

ks = xor_bytes(a1, c1)
target_pt = b'give me the flag'
target_ct = xor_bytes(ks, target_pt)

forged_tag = forge_tag(H, b'CryptoHack', c1, t1, b'CryptoHack', target_ct)
print(forged_tag)

def decrypt():
    data = requests.get(f"{BASE_URL}/decrypt/{iv.hex()}/{target_ct.hex()}/{forged_tag.hex()}/{b'CryptoHack'.hex()}/")
    return data.json()

flag = decrypt()["plaintext"]
print(bytes.fromhex(flag).decode())